### ISSUE TITLE
Getting an interval error in vite-imagetools in sveltekit...

### ISSUE THREAD

**Issue by rchrdnsh** [JonasKruckenberg/imagetools#426]
Getting this error when trying to use vite-imagetools defaultDirectives:

<img width="1438" alt="Screen Shot 2022-10-18 at 11 27 19 AM" src="https://user-images.githubusercontent.com/7884263/196515790-615b32e7-734c-4743-ab75-22a0fb2efcaf.png">

here is the text:

```js
11:27:07 AM [vite] Internal server error: vite-imagetools cannot find image with id "2e03bbb75783c9ee5c6345f7f878d29b6e148e7e," this is likely an internal error
      at file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite-imagetools/dist/index.mjs:89:31
      at call (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:48422:7)
      at next (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:48366:5)
      at Function.handle (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:48369:3)
      at Http2SecureServer.app (file:///Users/rchrdnsh/Code/Svelte/RYKR-kit/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:48234:37)
      at Http2SecureServer.emit (node:events:527:28)
      at Http2SecureServer.onServerStream (node:internal/http2/compat:883:10)
      at Http2SecureServer.emit (node:events:527:28)
      at ServerHttp2Session.sessionOnStream (node:internal/http2/core:2997:19)
      at ServerHttp2Session.emit (node:events:527:28)
```

...and here is what I'm doing for the defaultDirective:

```js
import { sveltekit } from '@sveltejs/kit/vite';
import { imagetools } from 'vite-imagetools';
import mkcert from 'vite-plugin-mkcert';

/** @type {import('vite').UserConfig} */

const supportedExtensions = ['webp', 'jpg', 'jpeg'];

const config = {
  ssr: {
    noExternal: [
      'svelte-stripe-js',
      'style-value-types',
      'popmotion',
      'framesync'
    ]
  },
  plugins: [
    sveltekit(),
    imagetools(
      {
        defaultDirectives: (url) => {
          const extension = url.pathname.substring(url.pathname.lastIndexOf('.') + 1);
          if (supportedExtensions.includes(extension)) {
            return new URLSearchParams({
              format: `webp;` + extension,
              width: `256;512;1024;2048`,
            });
          }
          return new URLSearchParams();
        }
      },
    ),
    mkcert({hosts: ['localhost', 'app.local']})
  ]
};

export default config;
```

and here is one of the images that is not working and how I'm using it in a markdown file:

```markdown
---
order: 9
status: featured
category: words
title: Groove
subtitle: What lives between the lines.
alt: So much history in the grooves of trees.
---

<script context="module">
  import image from './images/groove.jpg';
  metadata.image = image;
</script>
```

...where images are imported into mdsvex files using the a script module and then those files are living in a separate folder to the routes folder and then are iterated through in a route.

I'm expecting the defaultDirective to turn the image path string of:

```js
'./images/groove.jpg';
```

into:

```js
'./images/groove.jpg?width=256;512;1024;2048&format=webp;jpg'
```

...don't know if that is happening or not or what might be going wrong...

**Comment by JonasKruckenberg** [comment]
Weird, this error means it failed to find the transformed image in the cache which really shouldn't happen.

Are you injecting the images into the transformation pipeline through a plugin somehow?

**Comment by rchrdnsh** [comment]
aha!

So, did a really simple test...turns out...when I specify multiple sizes and feed that output into a plain `<img>` tag, rather than a `<picture>` tag, then it errors out like this...I think that's totally my bad...although maybe an error message that says...

"hey...dummy...you can't feed multiple images to an `<img>` tag...come on, moron...I mean you, Richard!"

...or something like that...we can tweak the wording :-)

I tried using the picture tag with...I think it's your example? not sure... anyway, it worked!

```js
<script>
  export let src;
  export let alt;
  export let article = false;
</script>

<picture>
  {#each Object.entries(src.sources) as [format, images]}
    <source srcset={images.map((i) => `${i.src}`).join(', ')} type={'image/' + format} /> 
  {/each}
  <img src={src.fallback.src} {alt} />
</picture>
```

...although...new issue...

...the incorrect size is being displayed...

I'll make a new issue for that one, however, thanks! XD

**Comment by roccopung** [comment]
Hey @rchrdnsh ! I am facing an identical issue but haven't solved it with the provided solution. Also using Markdown and sveltekit. My vite config is this:

```
imagetools({
			defaultDirectives: () => {
				return new URLSearchParams({
					format: `webp;avif;jpg`,
					width: `640;800;1280`,
					metadata: `width;format;src`,
				})
			},
			cache: {
				enabled: false,
				dir: './node_modules/.cache/imagetools',
				retention: 172800,
			},
		}),
```
		
this is my md file:

```
<script>
  import Picture from '$lib/components/picture.svelte'
  import Banner from './media/Banner1920x1080.jpg?'
</script>


<Picture meta={Banner}  alt="hello" loading="lazy" />
```

And this is how my Picture component is made:

```

<script>
	import { onMount } from "svelte"

	export let meta
	export let alt
	export let loading = undefined

	
	if (!(meta instanceof Array)) meta = [meta]

	let sources = new Map()
	let fallbackImage;

	meta.map((m) => sources.set(m.format, []))
	meta.map((m) => sources.get(m.format).push(m))



	onMount(async () => {
		fallbackImage = await sources.get([...sources.keys()].slice(-1)[0])[0]
	})
</script>

<picture>
	{#each [...sources.entries()] as [format, meta]}
		<source
			sizes="(min-width:1920px) 1280px, (min-width:1080px) 800px, (min-width:768px) 640px"
			type="image/{format}"
			srcset={meta.map((m) => `${m.src} ${m.width}w`).join(', ')}
		/>
	{/each}

	{#if fallbackImage}
		<img src={fallbackImage} {alt} {loading} />
	{/if}
</picture>

```

Do you have any idea where I might be wrong?

**Comment by roccopung** [comment]
Hey @rchrdnsh ! I am facing an identical issue but haven't solved it with the provided solution. Also using Markdown and sveltekit. My vite config is this:

```
imagetools({
			defaultDirectives: () => {
				return new URLSearchParams({
					format: `webp;avif;jpg`,
					width: `640;800;1280`,
					metadata: `width;format;src`,
				})
			},
			cache: {
				enabled: false,
				dir: './node_modules/.cache/imagetools',
				retention: 172800,
			},
		}),
```
		
this is my md file:

```
<script>
  import Picture from '$lib/components/picture.svelte'
  import Banner from './media/Banner1920x1080.jpg?'
</script>


<Picture meta={Banner}  alt="hello" loading="lazy" />
```

And this is how my Picture component is made:

```

<script>
	import { onMount } from "svelte"

	export let meta
	export let alt
	export let loading = undefined

	
	if (!(meta instanceof Array)) meta = [meta]

	let sources = new Map()
	let fallbackImage;

	meta.map((m) => sources.set(m.format, []))
	meta.map((m) => sources.get(m.format).push(m))



	onMount(async () => {
		fallbackImage = await sources.get([...sources.keys()].slice(-1)[0])[0]
	})
</script>

<picture>
	{#each [...sources.entries()] as [format, meta]}
		<source
			sizes="(min-width:1920px) 1280px, (min-width:1080px) 800px, (min-width:768px) 640px"
			type="image/{format}"
			srcset={meta.map((m) => `${m.src} ${m.width}w`).join(', ')}
		/>
	{/each}

	{#if fallbackImage}
		<img src={fallbackImage} {alt} {loading} />
	{/if}
</picture>

```

Do you have any idea where I might be wrong?
